### ISSUE TITLE
IElectricMinecart's ChargeHandler.balance method can be an issue

### ISSUE THREAD

**Issue by skyboy** [CovertJaguar/Railcraft-API#13]
The method `mods/railcraft/api/electricity/IElectricMinecart$ChargeHandler.balance` simply splits the charge of two handlers exactly evenly between them, with no regard for the capacity of the two handlers, potentially leading to a situation where a very large capacity handler and a low capacity handler are made to balance with each other, massively overflowing the smaller one.

**Comment by CovertJaguar** [comment]
This was considered in the design and determined that the cpu cycles that the checks cost wasn't worth the result. Additionally, ChargeHandler is final, so maxCapacity is _always_ 10000.
