### ISSUE TITLE
Use forge namespaced registry for track type and track kit

### ISSUE THREAD

**Issue by liach** [CovertJaguar/Railcraft-API#17]

**Comment by CovertJaguar** [comment]
I tried, it was horribly complicated and way overkill for my needs.

**Comment by liach** [comment]
Ah ok. I thought forge ones would help polling random kits.

**Comment by CovertJaguar** [comment]
If you can get it working sure, but after digging through the registry code for 45 minutes trying to understand how the hell it worked I gave up and just rolled my own.
